### ISSUE TITLE
:DevdocsFetch raises "nvim-devdocs: Error when fetching registery, exit code: 2"

### ISSUE THREAD

**Issue by russarr** [luckasRanarison/nvim-devdocs#10]
I have an error when running the command :DevdocsFetch
First message: "Fetching DevDocs registery..."
And then error message: "nvim-devdocs: Error when fetching registery, exit code: 2"
Setup using Lazy with default config
NVIM v0.9.1
OS: Windows 10 Pro 22H2

**Comment by luckasRanarison** [comment]
The plugin is using `curl` for making requests and it seems to be an internal error according to [this](https://everything.curl.dev/usingcurl/returns)

`2 - Failed to initialize. This is mostly an internal error or a problem with the libcurl installation or system libcurl runs in.`

**Comment by russarr** [comment]
I found out that there is a problem with ssl certificates. 
Unfortunately, I have not been able to solve it. Is it possible to manually download the necessary files and save them to the appropriate directory?

**Comment by luckasRanarison** [comment]
It's not possible because of the fetched data still needs to be processed before being written to the disk. I'll see if I can do something to fix this.

**Comment by russarr** [comment]
The problem is solved. Damn antivirus. Issue can be closed

**Comment by Andyson007** [comment]
How did this get solved?
