### ISSUE TITLE
no such file or directory: index.json

### ISSUE THREAD

**Issue by I-Own-You** [luckasRanarison/nvim-devdocs#11]
<h2> Hi
<h3>I installed your plugin using lazy.nvim.<br>
I did use DevDocsFetch, something has been created.<br>
Then i tried DevDocsInstall javascript (or whatever language), and i got this error.<br>
<br>

![Screenshot from 2023-08-12 13-13-54](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/7f1d27b1-c79f-48e3-9189-66f3b4a96f1f)
<br>
<h3>This is my config:
<br>
<br>

![Screenshot from 2023-08-12 13-20-12](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/d6bf2ffa-30f4-4244-9321-12075b40bfb1)
![Screenshot from 2023-08-12 13-21-16](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/e26e23e5-4022-4906-84f2-b81c9edb2444)

<h4> UPD: when i use the command DevDocsInstall without arguments, the error appears, but then the telescope picker appears, and i can install the documentation, and it works.
<br>
<br>

**Comment by luckasRanarison** [comment]
Thanks for the report. I've made a dumb mistake, it should be fixed now

**Comment by I-Own-You** [comment]
> Thanks for the report. I've made a dumb mistake, it should be fixed now

not dumb, you just forget 🥇 
yes, its fixed 🍾

**Comment by luckasRanarison** [comment]
xD, I'm working on that don't worry, #4. 
You can use glow.nvim for now.

**Comment by I-Own-You** [comment]
> xD, I'm working on that don't worry, #4. You can use glow.nvim for now.

damn this is a killer plugin, i didnt know about devdocs, glad i just clicked on the phone notification, its mindblowing, literally offline docs available in the neovim, good job
