### ISSUE TITLE
Make a way to go back to the picker window

### ISSUE THREAD

**Issue by I-Own-You** [luckasRanarison/nvim-devdocs#19]
<h1>Feature request</h1>

<p>It would be nice, after closing the markdown file, to go back to the picker window</p>
<p>Or at least, setting a filetype to the floating window that is opening, so people could trigger an event and trigger :DevdocsOpenCurrenFloat again, after closing the markdown.</p>
(at least i did the trigger event with filetype, because :Glow set a filetype, and i could use it</p>

**Comment by luckasRanarison** [comment]
The plugin is using **Telescope** picker and telescope pickers are cached, you can use `:Telescope resume` to resume your last search.

**Comment by I-Own-You** [comment]
> The plugin is using **Telescope** picker and telescope pickers are cached, you can use `:Telescope resume` to resume your last search.

i meant another thing, but you gave me an idea, thanks!

**Comment by luckasRanarison** [comment]
> i meant another thing, but you gave me an idea, thanks!
Sorry if I misunderstood it, but I still don't get it...
