### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by I-Own-You** [luckasRanarison/nvim-devdocs#20]
When i am in .py file, i try to run :DevdocOpenCurrent or :DevdocOpenCurrentFloat</p> and it says `python documentation is not installed`, even thought i have installed python-3.11. 

I never issued such a problem because i opened the plugin with :DevdocOpenFloat everytime.</p>

**Comment by luckasRanarison** [comment]
It's not a bug it was just missing in the filetype list, it should work now
```lua
local M = {
  ["sh"] = "bash",
  ["lua"] = "lua-5.4",
  ["vue"] = "vue-3",
  ["dart"] = "dart-2",
  ["ruby"] = "ruby-3.2",
  ["twig"] = "twig-3",
  ["less"] = "less-4",
  ["python"] = "python-3.11",
  ["javascriptreact"] = "react",
  ["typescriptreact"] = "react",
}
```
