### ISSUE TITLE
:DevdocsFetch raises "nvim-devdocs: Error when fetching registery, exit code: 2"

### ISSUE THREAD

**Issue by Andyson007** [luckasRanarison/nvim-devdocs#31]
I know that this issue has already been addressed, but without any solutions.

**Comment by Pagliacii** [comment]
It seems like the `plenary.nvim` was using a wrong curl. Executing the `curl -sSL https://documents.devdocs.io/rust/index.json?1690404053` manually was fetching file successfully.

**Comment by Andyson007** [comment]
And how do you fiz this?

**Comment by Andyson007** [comment]
Only difference beeing that I'm using packer and not lazy.

**Comment by luckasRanarison** [comment]
It's not related to the package manager or the plugin. The issue is either a problem with plenary or curl itself, the error code 2 refers to an internal error from `curl`.

**Comment by Pagliacii** [comment]
Oh no, it seems the Windows curl doesn't support the `--compressed` option. You can execute this code block inside Neovim:

```lua
local curl = require("plenary.curl")

vim.print(curl.get("https://devdocs.io/docs.json", {
  dry_run = true,
}))
```

Copy all code and press the `:` key into the command mode, enter this to execute: `lua <c-r>*<cr>`. The result should be like this:

```lua
{ "-sSL", "-D", "C:\\Users\\Username\\AppData\\Local\\Temp\\plenary_curl_a93748a1.headers", "--compressed", "-X", "GET", "https://devdocs.io/docs.json" }
```

And then you can execute this command `curl -sSL --compressed -X GET https://devdocs.io/docs.json` in the terminal (I'm using PowerShell btw), it will complain:

```
λ curl -sSL --compressed -X GET https://devdocs.io/docs.json
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information

λ echo $LASTEXITCODE
2
```

So I think the solution is to change your curl path, don't use the Windows default one.

P.S. You can use this code block to check which curl will be used in plenary:

```lua
local Job = require'plenary.job'

Job:new({
  command = 'rg',
  args = { '--files' },
  on_exit = function(j, return_val)
    vim.print(vim.inspect(return_val))
    vim.print(vim.inspect(j:result()))
  end,
}):start()
```

P.P.S. If you're using the `scoop` package manager, you can install the `curl` by this command: `scoop install curl`. And editing your environment variables, keep the `<you scoop path>\shims` before the "C:\Windows\System32". After that, everything should be fine.

**Comment by Andyson007** [comment]
And how could i replace the curl file used by plenary?

**Comment by Pagliacii** [comment]
I'm afraid you could not do that easily.

See [code](https://github.com/nvim-lua/plenary.nvim/blob/0dbe561ae023f02c2fb772b879e905055b939ce3/lua/plenary/curl.lua#L256-L259) below:

```lua
  local job_opts = {
    command = "curl",
    args = args,
  }
```

`plenary.nvim` doesn't provide an option to specify the `curl` path, it just finds that in your path environment variables.

**Comment by Andyson007** [comment]
yeah Ok it worked to just add the choco bin path in front of sys32 in the path idk why it didn't work previously

**Comment by Andyson007** [comment]
Actually I get this error now. Should i create a new issue for this?

Error executing vim.schedule lua callback: ...acker\start\nvim-devdocs/lua/nvim-devdocs/transpiler.lua:340: attempt to perform arithmetic on local 'col_len' (a nil value)
stack traceback:
        ...acker\start\nvim-devdocs/lua/nvim-devdocs/transpiler.lua:340: in function 'eval_table'
        ...acker\start\nvim-devdocs/lua/nvim-devdocs/transpiler.lua:225: in function 'eval'
        ...acker\start\nvim-devdocs/lua/nvim-devdocs/transpiler.lua:388: in function 'fn'
        ...4\share\nvim\runtime/lua/vim/treesitter/languagetree.lua:341: in function 'for_each_tree'
        ...acker\start\nvim-devdocs/lua/nvim-devdocs/transpiler.lua:383: in function 'html_to_md'
        ...ack\packer\start\nvim-devdocs/lua/nvim-devdocs/build.lua:39: in function 'build_docs'
        ...acker\start\nvim-devdocs/lua/nvim-devdocs/operations.lua:72: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>

**Comment by Pagliacii** [comment]
See this #32
