### ISSUE TITLE
Use custom commands to render markdown 

### ISSUE THREAD

**Issue by luckasRanarison** [luckasRanarison/nvim-devdocs#4]
Use tools like glow to render documentations inside a terminal buffer

**Comment by gipo355** [comment]
Exactly the first thing i did! fetching the doc and immediately using glow on it

**Comment by mvaldes14** [comment]
was gonna create an issue for this, so yeah something like glow works perfectly for this cause seeing raw markdown in a buffer isn't exactly functional... id rather just use the browser

**Comment by I-Own-You** [comment]
> was gonna create an issue for this, so yeah something like glow works perfectly for this cause seeing raw markdown in a buffer isn't exactly functional... id rather just use the browser

<h3> As a workaround you could use the same command you open DevDocsOpenFloat and :Glow, and closing the DevDocsOpenFloat markdown but not the :Glow variant, closing it with q also. init.lua:</h3>


```lua
vim.cmd[[
augroup AutoCloseMarkdownGlow
  autocmd!
  autocmd FileType markdown,glowpreview nnoremap <buffer> q :q<CR>
augroup END
]]

vim.cmd[[
augroup MarkdownKeymaps
  autocmd!
  autocmd FileType markdown nnoremap <buffer> <leader>dd :lua MyGlow()<CR>
  autocmd FileType glowpreview nnoremap <buffer> <leader>dd :<CR>
augroup END
]]

function MyGlow()
  vim.cmd('Glow')
  for _, winid in ipairs(vim.fn.getwininfo()) do
    local bufnr = winid.bufnr
    local filetype = vim.api.nvim_buf_get_option(bufnr, 'filetype')
    if filetype == 'markdown' then
      vim.cmd('bw ' .. bufnr)
      return
    end
  end
end

-- Keymap for DevdocsOpenFloat
vim.api.nvim_set_keymap("n", "<leader>dd", ":DevdocsOpenFloat<CR>", {noremap = true, silent = true})
```
<h3>The only downside is that the first time you will try to do it, it will close the buffer because of plugin loading. But after the first one, it will always work. But you can adjust i guess with some time.sleep from lua</h3>

[Screencast from 2023-08-12 16-32-04.webm](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/a684f145-69ab-4f36-a45f-bf0dc6f35d81)

**Comment by luckasRanarison** [comment]
New in 5b6ba3c 
Good news guys... You can now use custom cmds for previewing docs! Checkout the config options for more details.
It's still not available for the telescope previewer however, I'm still thinking on how to improve the performance...

**Comment by emmanueltouzery** [comment]
I tried the glow support by adding `previewer_cmd = 'glow',`.

At first I was getting nothing at all displayed. But I was using glow 1.4.1. I upgraded it to 1.5.1 and now I'm getting something displayed, and it's the glow output, for instance links are handled differently.. However I'm getting no syntax highlighting at all. Not sure why for now.

I'm using linux.

**Comment by emmanueltouzery** [comment]
ok, with the --s flags you give in the documentation i get syntax highlighting :+1:

**Comment by I-Own-You** [comment]
> ok, with the --s flags you give in the documentation i get syntax highlighting 👍

could you show me your setup options ?
i cant make it work for me

**Comment by I-Own-You** [comment]
> New in [5b6ba3c](https://github.com/luckasRanarison/nvim-devdocs/commit/5b6ba3c632d014761cfa87dc4e967c0e5c4a086f) Good news guys... You can now use custom cmds for previewing docs! Checkout the new config options for more details. It's still not available for the telescope previewer however, I'm still thinking on how to improve the performance...
> 
> ![image](https://user-images.githubusercontent.com/101930730/260244811-764be3ba-8158-4c5b-a02f-02e02d08e1c4.png)

would you mind sharing your colorscheme theme and wallpaper background and terminal name ? 🍾

**Comment by emmanueltouzery** [comment]
@I-Own-You I just used the settings from the readme, namely:
```lua
  previewer_cmd = 'glow'
  cmd_args = { "-s", "dark", "-w", "80" }
```

**Comment by luckasRanarison** [comment]
All pickers have previews now and support custom commands so I think I can close this.
