### ISSUE TITLE
How can I add additional filetypes eg Clojure?

### ISSUE THREAD

**Issue by oryband** [luckasRanarison/nvim-devdocs#53]
I would like to add `.clj` and `.cljs` filetypes to open `clojure-1.11`. How can I do that?

**Comment by luckasRanarison** [comment]
You can't define custom filetypes in the user config for now. The filetypes are defined in [filetypes.lua](https://github.com/luckasRanarison/nvim-devdocs/blob/master/lua/nvim-devdocs/filetypes.lua), I could add it for a quickfix but there's already a feature request for making filetypes more flexible #30 and it's a better idea than extending the above file. I'm working on other things now but that should be possible soon.

**Comment by luckasRanarison** [comment]
Closure docs should be automatically detected now, and you can now define custom mappings with the new `filetypes` config.
