### ISSUE TITLE
Run Out Of Memory(Ram)

### ISSUE THREAD

**Issue by I-Own-You** [luckasRanarison/nvim-devdocs#65]
<h2>Hi again!</h2>
<h4>I tried to install a very large documentation:</h4>  

`DevdocsInstall dom`

It started downloading and my memory started bouncing up to my limit( i have 8gb ) and down, and eventually it closes the neovim and the documentation isnt built.

**Comment by I-Own-You** [comment]
At first, `nvim --headless +"DevdocsInstall dom"` didnt work. <br>But i managed to enter in recovery mode with all turned off, so i managed to install it.

**Comment by luckasRanarison** [comment]
The high ram usage is really annoying, my computer also freezes everytime. For some reason parsing takes a lot of RAM. I've already tried a lot of things see #24, but I haven't came up with a good solution yet.

**Comment by djmbritt** [comment]
> At first, `nvim --headless +"DevdocsInstall dom"` didnt work. But i managed to enter in recovery mode with all turned off, so i managed to install it.

Hi, which command did you use to get in to recovery mode?
I'm trying:
```bash
nvim --headless -r  +"DevdocsInstall rust"
```
But I'm having no luck.

**Comment by I-Own-You** [comment]
> > At first, `nvim --headless +"DevdocsInstall dom"` didnt work. But i managed to enter in recovery mode with all turned off, so i managed to install it.
> 
> Hi, which command did you use to get in to recovery mode? I'm trying:
> 
> ```shell
> nvim --headless -r  +"DevdocsInstall rust"
> ```
> 
> But I'm having no luck.

by recovery mode i meant cli only interfce of arch so i had as low as possible ram
