### ISSUE TITLE
lua-5.4 docs are all one giant document

### ISSUE THREAD

**Issue by semanticart** [luckasRanarison/nvim-devdocs#8]
I Installed lua-5.4 docs and while the search terms populate correctly, selecting a term just sends you to the top of the 4k-line document.

It also renders the entire document in the preview field as you type which can be a little laggy.

I'm on the latest (at time of writing):

https://github.com/luckasRanarison/nvim-devdocs/assets/8633/ea838a7d-9454-4820-998e-067df5c7d10e

LMK if I can provide more details. I love this plugin.

**Comment by luckasRanarison** [comment]
Thanks for giving my plugin a try :). It is actually a known issue #1,  I'm still making experiments `vim.fn.search()`, please keep waiting a little bit, I'll try to fix this asap.

**Comment by luckasRanarison** [comment]
I'm also thinking about using asynchronous functions to avoid blocking.

**Comment by semanticart** [comment]
Thanks, and sorry for missing the existing issue.

**Comment by luckasRanarison** [comment]
It's fine. Concerning the lua docs and all the documentations in general I think it would be hard to always move directly to the section being searched. Here is a sample of the entries for the lua docs:

![2023-08-12-095154_hyprshot](https://github.com/luckasRanarison/nvim-devdocs/assets/101930730/eabcb301-0762-4dbc-a860-38d403755baa)

The `path` refers to the HTML class and id in the original HTML documentation but these are omitted when converting the HTML to markdown. The best we can do is to get the first part of the path which refers to the actual documentation entry. In the case of the lua docs, there's only one entry: `index`.

![2023-08-12-095117_hyprshot](https://github.com/luckasRanarison/nvim-devdocs/assets/101930730/1b98d10f-6865-4af7-a9d1-e43cba07a68a)

We can still use `vim.fn.search()` but it won't get it right every time.

**Comment by luckasRanarison** [comment]
Update: It's actually possible! And I'll track this issue with #17

**Comment by semanticart** [comment]
Awesome, thanks!

**Comment by luckasRanarison** [comment]
With #21, jumping works for normal files now. But for the moment it doesn't work in the picker previewer and when rendering with custom cmd.

**Comment by benelan** [comment]
Would it be possible to split the single file doc sources into multiple files during transpilation based on the headers, or whatever you're using to populate telescope entries? 

Jumping works great now but it still takes a long time to render via glow and the telescope previewer needs to rerender when changing entries even though the content doesn't change.

Thanks for making this by the way!

**Comment by luckasRanarison** [comment]
That's what I'm going to do, thanks for your interest in the project.

**Comment by luckasRanarison** [comment]
Closing this as completed see #42
